// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiXnMxxrp7C4ixGk9aKRTWGcHR7_dnUMo',
    appId: '1:365099356606:web:4674ce870b335e60aa29ef',
    messagingSenderId: '365099356606',
    projectId: 'smart-canteen-24611',
    authDomain: 'smart-canteen-24611.firebaseapp.com',
    storageBucket: 'smart-canteen-24611.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoiCi1xTEq-sIDL2z8ItBk8y9eEhcmB0c',
    appId: '1:365099356606:android:2d24c872c2af1e1aaa29ef',
    messagingSenderId: '365099356606',
    projectId: 'smart-canteen-24611',
    storageBucket: 'smart-canteen-24611.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIe93-tOeFnPWO_FHU3m6S9TC2gnqwlgw',
    appId: '1:365099356606:ios:1e569d6ea1d91177aa29ef',
    messagingSenderId: '365099356606',
    projectId: 'smart-canteen-24611',
    storageBucket: 'smart-canteen-24611.firebasestorage.app',
    iosBundleId: 'com.example.mahiq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIe93-tOeFnPWO_FHU3m6S9TC2gnqwlgw',
    appId: '1:365099356606:ios:1e569d6ea1d91177aa29ef',
    messagingSenderId: '365099356606',
    projectId: 'smart-canteen-24611',
    storageBucket: 'smart-canteen-24611.firebasestorage.app',
    iosBundleId: 'com.example.mahiq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiXnMxxrp7C4ixGk9aKRTWGcHR7_dnUMo',
    appId: '1:365099356606:web:d829237b3bd566dbaa29ef',
    messagingSenderId: '365099356606',
    projectId: 'smart-canteen-24611',
    authDomain: 'smart-canteen-24611.firebaseapp.com',
    storageBucket: 'smart-canteen-24611.firebasestorage.app',
  );
}
